mybatis.type-aliases-package=cpct.taurus.entity
mybatis.mapper-locations=classpath:mapper/*.xml
mapper.mappers=cpct.taurus.util.MyMapper
mapper.not-empty=false
mapper.identity=MYSQL

pagehelper.helperDialect=mysql
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql

logging.level.cpct.taurus.mapper=debug